# Generated by Django 5.1.1 on 2024-09-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTransportes', '0003_alter_ruta_distancia_alter_ruta_localidad_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
