# Generated by Django 5.1.1 on 2024-10-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTransportes', '0005_alter_paquete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='localidades_intermedias',
            field=models.ManyToManyField(blank=True, related_name='rutas_intermedias', to='RedTransportes.localidad'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='localidad_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_fin', to='RedTransportes.localidad'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='localidad_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_inicio', to='RedTransportes.localidad'),
        ),
    ]
