# Generated by Django 5.1.1 on 2024-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedTransportes', '0007_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
